#!/usr/bin/env Rscript
source("common.R")
ctx <- context_init()

code <- c(
  "#!/usr/bin/env bash",
  "set -ex",
  "HERE=$(dirname $0)",
  "cd $HERE",
  sprintf("rrq-worker %s %s", ctx$root$path, ctx$name))

writeLines(code, "worker")
Sys.chmod("worker", "0755")
