#!/usr/bin/env Rscript
"Usage:
  rrq_worker <root> <id>
" -> usage


get_redis <- function(timeout = 10, poll = 1) {
  cfg <- redux::redis_config()
  message(sprintf("Trying to connect to redis at %s", cfg$url))
  tstop <- Sys.time() + timeout
  repeat {
    con <- tryCatch(
      redux::hiredis(cfg),
      error = identity)
    if (inherits(con, "redis_api")) {
      message(" OK")
      return(con)
    } else if (Sys.time() < tstop) {
      message("Failed to connect to redis in time")
      stop(con)
    }
    message(".")
    Sys.sleep(poll)
  }
}


message("Worker running in ", getwd())
args <- docopt::docopt(usage)
ctx <- context::context_read(args$id, args$root)
con <- get_redis()
rrq::rrq_worker(ctx, con, time_poll = 3)
